name: CI golang
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "unitest"
    steps:
      - uses: actions/checkout@v3
      - name: "setup go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3
